import { Geist, Geist_Mono,Outfit,Rubik} from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";


const geistSans = Outfit({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <GoogleOneTap />
      <body className={ geistSans.className }>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
